### PR TITLE
Fixed typo and removed reference to GitBook

### LINKED ISSUE #5: How to contribute?
Hello @concentrateddon, others,

I cloned this repo, created a branch, committed something, and wanted to push my branch back as a Pull request, but I get 403 access denied. What's your preferred flow?

``` git
> git push -u origin Remove_GitBook_references
remote: Permission to devops-collective-inc/big-book-of-powershell-gotchas.git denied to Jawz84.
fatal: unable to access 'https://github.com/devops-collective-inc/big-book-of-powershell-gotchas.git/': The requested URL returned error: 403
```

Thanks :)

### PR DESCRIPTION
**Pull request by Jawz84**
Hello Don, others,

I wanted to contribute to this great material, and this is my first baby step. 

I wanted to update the About.md because a small typo cought my eye, next thing i knew, I also wanted to make sure the text reflected the status of LeanPub/GitBook.

Also, added a CONTRIBUTING.md, which should fix #5 :-)

### CODE REVIEW

**Comment by concentrateddon** [comment]
Appreciate it! If you can repeat the same fix (if relevant) in the Spanish version, that'd be awesome!

**Comment by Jawz84** [comment]
Spanish, hmm. I speak four languages, but that's not one of 'em. I'll see what I can do. But I sure can't proofread it. Do you know someone who could?

**Comment by concentrateddon** [comment]
Yup, ping @ATorresTatis on Twitter. He did the original translations.

**Comment by Jawz84** [comment]
Will do. See pr in ~-Spanish repo.

**Pull request merged**
